import { LucideIcon, FileText, ShoppingBag, HelpCircle, Star, MapPin, Calendar, Users } from 'lucide-react';

export interface SchemaField {
  id: string;
  label: string;
  type: 'text' | 'url' | 'date' | 'number' | 'textarea';
  required: boolean;
  placeholder: string;
  description: string;
}

export interface SchemaType {
  type: string;
  icon: LucideIcon;
  fields: SchemaField[];
}

export const schemaTypes: SchemaType[] = [
  {
    type: 'Article',
    icon: FileText,
    fields: [
      {
        id: 'headline',
        label: 'Headline',
        type: 'text',
        required: true,
        placeholder: 'Article headline',
        description: 'The title of the article',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Brief description of the article',
        description: 'A short summary of the article content',
      },
      {
        id: 'author.name',
        label: 'Author Name',
        type: 'text',
        required: true,
        placeholder: 'Author name',
        description: 'The name of the article author',
      },
      {
        id: 'datePublished',
        label: 'Date Published',
        type: 'date',
        required: true,
        placeholder: 'YYYY-MM-DD',
        description: 'The date the article was first published',
      },
      {
        id: 'url',
        label: 'URL',
        type: 'url',
        required: true,
        placeholder: 'https://example.com/article',
        description: 'The URL where the article is published',
      },
      {
        id: 'image',
        label: 'Image URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/image.jpg',
        description: 'URL of the article\'s featured image',
      },
    ],
  },
  {
    type: 'Product',
    icon: ShoppingBag,
    fields: [
      {
        id: 'name',
        label: 'Product Name',
        type: 'text',
        required: true,
        placeholder: 'Product name',
        description: 'The name of the product',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Product description',
        description: 'A detailed description of the product',
      },
      {
        id: 'offers.price',
        label: 'Price',
        type: 'number',
        required: true,
        placeholder: '99.99',
        description: 'The price of the product',
      },
      {
        id: 'offers.priceCurrency',
        label: 'Currency',
        type: 'text',
        required: true,
        placeholder: 'USD',
        description: 'The currency of the price (e.g., USD, EUR)',
      },
      {
        id: 'aggregateRating.ratingValue',
        label: 'Rating',
        type: 'number',
        required: false,
        placeholder: '4.5',
        description: 'The average rating of the product (1-5)',
      },
      {
        id: 'aggregateRating.reviewCount',
        label: 'Review Count',
        type: 'number',
        required: false,
        placeholder: '100',
        description: 'The total number of reviews',
      },
      {
        id: 'url',
        label: 'Product URL',
        type: 'url',
        required: true,
        placeholder: 'https://example.com/product',
        description: 'The URL of the product page',
      },
      {
        id: 'image',
        label: 'Image URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/product.jpg',
        description: 'URL of the product image',
      },
    ],
  },
  {
    type: 'FAQPage',
    icon: HelpCircle,
    fields: [
      {
        id: 'mainEntity[0].question',
        label: 'Question 1',
        type: 'text',
        required: true,
        placeholder: 'What is...?',
        description: 'The first FAQ question',
      },
      {
        id: 'mainEntity[0].answer',
        label: 'Answer 1',
        type: 'textarea',
        required: true,
        placeholder: 'The answer to the question...',
        description: 'The answer to the first question',
      },
      {
        id: 'mainEntity[1].question',
        label: 'Question 2',
        type: 'text',
        required: false,
        placeholder: 'How do I...?',
        description: 'The second FAQ question',
      },
      {
        id: 'mainEntity[1].answer',
        label: 'Answer 2',
        type: 'textarea',
        required: false,
        placeholder: 'The answer to the question...',
        description: 'The answer to the second question',
      },
    ],
  },
  {
    type: 'Review',
    icon: Star,
    fields: [
      {
        id: 'itemReviewed.name',
        label: 'Item Name',
        type: 'text',
        required: true,
        placeholder: 'Name of reviewed item',
        description: 'The name of the item being reviewed',
      },
      {
        id: 'reviewRating.ratingValue',
        label: 'Rating',
        type: 'number',
        required: true,
        placeholder: '4.5',
        description: 'The rating given in the review (1-5)',
      },
      {
        id: 'author.name',
        label: 'Author Name',
        type: 'text',
        required: true,
        placeholder: 'Reviewer name',
        description: 'The name of the reviewer',
      },
      {
        id: 'reviewBody',
        label: 'Review Text',
        type: 'textarea',
        required: true,
        placeholder: 'Full text of the review',
        description: 'The complete text of the review',
      },
      {
        id: 'datePublished',
        label: 'Review Date',
        type: 'date',
        required: true,
        placeholder: 'YYYY-MM-DD',
        description: 'The date the review was published',
      },
    ],
  },
  {
    type: 'LocalBusiness',
    icon: MapPin,
    fields: [
      {
        id: 'name',
        label: 'Business Name',
        type: 'text',
        required: true,
        placeholder: 'Business name',
        description: 'The name of the business',
      },
      {
        id: 'address.streetAddress',
        label: 'Street Address',
        type: 'text',
        required: true,
        placeholder: '123 Main St',
        description: 'The street address of the business',
      },
      {
        id: 'address.addressLocality',
        label: 'City',
        type: 'text',
        required: true,
        placeholder: 'City',
        description: 'The city where the business is located',
      },
      {
        id: 'address.addressRegion',
        label: 'State',
        type: 'text',
        required: true,
        placeholder: 'State',
        description: 'The state where the business is located',
      },
      {
        id: 'address.postalCode',
        label: 'Postal Code',
        type: 'text',
        required: true,
        placeholder: '12345',
        description: 'The postal code of the business location',
      },
      {
        id: 'telephone',
        label: 'Phone Number',
        type: 'text',
        required: false,
        placeholder: '+1-234-567-8900',
        description: 'The business phone number',
      },
      {
        id: 'url',
        label: 'Website URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com',
        description: 'The URL of the business website',
      },
    ],
  },
  {
    type: 'Event',
    icon: Calendar,
    fields: [
      {
        id: 'name',
        label: 'Event Name',
        type: 'text',
        required: true,
        placeholder: 'Event name',
        description: 'The name of the event',
      },
      {
        id: 'startDate',
        label: 'Start Date',
        type: 'date',
        required: true,
        placeholder: 'YYYY-MM-DD',
        description: 'The start date of the event',
      },
      {
        id: 'endDate',
        label: 'End Date',
        type: 'date',
        required: false,
        placeholder: 'YYYY-MM-DD',
        description: 'The end date of the event',
      },
      {
        id: 'location.name',
        label: 'Venue Name',
        type: 'text',
        required: true,
        placeholder: 'Venue name',
        description: 'The name of the venue where the event is held',
      },
      {
        id: 'location.address',
        label: 'Venue Address',
        type: 'text',
        required: true,
        placeholder: 'Full address',
        description: 'The complete address of the venue',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Event description',
        description: 'A description of the event',
      },
      {
        id: 'offers.price',
        label: 'Ticket Price',
        type: 'number',
        required: false,
        placeholder: '99.99',
        description: 'The price of admission',
      },
      {
        id: 'offers.priceCurrency',
        label: 'Currency',
        type: 'text',
        required: false,
        placeholder: 'USD',
        description: 'The currency of the ticket price',
      },
    ],
  },
  {
    type: 'Organization',
    icon: Users,
    fields: [
      {
        id: 'name',
        label: 'Organization Name',
        type: 'text',
        required: true,
        placeholder: 'Organization name',
        description: 'The name of the organization',
      },
      {
        id: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        placeholder: 'Organization description',
        description: 'A description of the organization',
      },
      {
        id: 'url',
        label: 'Website URL',
        type: 'url',
        required: true,
        placeholder: 'https://example.com',
        description: 'The URL of the organization\'s website',
      },
      {
        id: 'logo',
        label: 'Logo URL',
        type: 'url',
        required: false,
        placeholder: 'https://example.com/logo.png',
        description: 'The URL of the organization\'s logo',
      },
      {
        id: 'contactPoint.telephone',
        label: 'Phone Number',
        type: 'text',
        required: false,
        placeholder: '+1-234-567-8900',
        description: 'The organization\'s contact phone number',
      },
      {
        id: 'contactPoint.email',
        label: 'Email',
        type: 'text',
        required: false,
        placeholder: 'contact@example.com',
        description: 'The organization\'s contact email',
      },
      {
        id: 'address',
        label: 'Address',
        type: 'text',
        required: false,
        placeholder: 'Full address',
        description: 'The organization\'s physical address',
      },
    ],
  },
];